import './globals.css'
import Providers from '@components/Providers';
import { Provider } from 'react-redux'
import store from '../store/store';


export const metadata = {
  title: 'connecxo',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <Providers>

        <body >{children}</body>

      </Providers>
    </html>
  )
}
