import './globals.css'
import Providers from '@components/Providers';

export const metadata = {
  title: 'connecxo',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body >{children}</body>
      </Providers>
    </html>
  )
}
